<?php $_order = $this->getOrder(); ?>
<?php $_shippingAddress = $_order->getShippingAddress() ?>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-russify"><?php echo $this->__('Russify.me Address Validation') ?></h4>
        </div>
        <fieldset class="russify-np">
            <div>
                <p><?php echo $this->__('Current shipping address:') ?></p>
                <address>
                    <?php echo Mage::helper('procommerz_russify')->getFormattedAddress($_shippingAddress) ?>
                </address>
            </div>

            <div id="russify_box">
               <?php echo $this->getChildHtml('status')?>
            </div>

            <div id="russify_loading" style="display: none; text-align: center;">
                <span>
                    <img src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>" alt="<?php echo Mage::helper('adminhtml')->__('Loading...') ?>"/>
                    <br/><?php echo Mage::helper('adminhtml')->__('Refreshing...') ?>
                </span>
            </div>
        </fieldset>
    </div>
</div>
<div class="clear"></div>
<script type="text/javascript">
    //<![CDATA[
    var russifyLoading = $('russify_loading');
    var resultBox = $('result');
    var usageBlock = Element.extend($('russify_box'));
    var address = <?php echo json_encode(Mage::helper('procommerz_russify')->prepareRequestArray($_shippingAddress)) ?>;
    var validateAddressUri = "<?php echo $this->getUrl('russify/validation/check', array('_forced_secure' => $this->getRequest()->isSecure())) ?>";

    validate = function() {
        russify_box.hide();
        russifyLoading.show();
        Ajax.Responders.unregister(varienLoaderHandler.handler);
        (function displayUsage() {
            new Ajax.Request(validateAddressUri,{
                parameters: {isAjax: 1, method: 'POST', address: Object.toJSON(address)},
                onSuccess: function(t) {
//                    russify_box.remove();
                    var result = t.responseJSON.result;
                    usageBlock.insert({after: result});
                    russify_box.show();
                    russifyLoading.hide();
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    russifyLoading.hide();
                    russify_box.show();
                }
            });
        })();
        Ajax.Responders.register(varienLoaderHandler.handler);
    }
    //]]>
</script>