<?php
/**
 * Validation Russify template
 *
 * @package    Procommerz_Russify
 * @author     Denis Kolesnichenko <denis@mobiquest.ru>
 */
?>
<?php $_helper = Mage::helper('procommerz_russify'); ?>
<?php if ($this->getOrderId()): ?>
    <?php $_orderId = $this->getOrderId(); ?>
<?php else:?>
    <?php $_orderId = $this->getOrder()->getEntityId(); ?>
<?php endif; ?>

<div id="russify_box">
    <?php if($_results = $this->getResult()) :?>
        <div class="not-validated">
            <div class="icon-wrapper">
                <i class="icon-picture"></i>
            </div>
            <p><?php echo $this->__('Address validated, check possible alternatives:') ?></p>
        </div>
        <div class="clear"></div>
        <div id="russify-result">
            <form action="#" method="post" id="alternative-form">
                <ul id="alternative-links-list" class="options-list">
                    <li>
                        <input id ="updateAddress" class="validate-one-required-by-name" type="radio" name="first" value='<?php echo serialize($_results) ?>'><?php echo implode(', ', $_results) ?><br>
                    </li>
                </ul>
            </form>
            <hr/>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
                <a class="form-button" href="#" onclick="updateRussify()" ><?php echo $this->__('Update Address') ?></a>
            </div>
        </div>

        <div class="clear"></div>
    <?php else: ?>
        <?php $_validateStatus = $_helper->getRussifyStatus($_orderId); ?>

        <?php if($_validateStatus == 'VALID'): ?>
            <div class="f-left validated">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Adress is valid') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
            </div>
        <?php elseif($_validateStatus == 'INVALID'): ?>
            <div class="f-left invalid">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Adress Invalid') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
            </div>
        <?php else:?>
            <div class="f-left not-validated">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Not Validated') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Validate') ?></a>
            </div>
        <?php endif;?>
    <?php endif; ?>
    <div class="clear"></div>
</div>
