<?php
/**
 * Validation Russify template
 *
 * @package    Procommerz_Russify
 * @author     Denis Kolesnichenko <denis@mobiquest.ru>
 */
?>
<?php $_helper = Mage::helper('procommerz_russify'); ?>
<?php if ($this->getOrderId()): ?>
    <?php $_orderId = $this->getOrderId(); ?>
<?php else:?>
    <?php $_orderId = $this->getOrder()->getEntityId(); ?>
<?php endif; ?>

<div id="russify_box">
    <?php if($_results = $this->getResult()) :?>
        <div class="not-validated">
            <div class="icon-wrapper">
                <i class="icon-picture"></i>
            </div>
            <p><?php echo $this->__('Address validated, check possible alternatives:') ?></p>
        </div>
        <div class="clear"></div>
        <div id="russify-result">
            <form action="#" method="post" id="alternative-form">
                <?php $_lastKey = end(array_keys($_results)); ?>
                <?php foreach($_results as $_key => $_value): ?>
                    <input
                    id ="updateAddress_<?php echo $_key; ?>"
                    class="<?php echo ($_key == $_lastKey) ? 'validate-one-required' : '' ?>"
                    type="radio" name="group1"
                    value='<?php echo serialize($_value) ?>'>
                    <?php echo implode(', ',get_object_vars($_value)) ?>
                    <br>
                <?php endforeach; ?>
            </form>
            <hr/>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
                <a class="form-button" href="#" onclick="updateRussify()" ><?php echo $this->__('Update Address') ?></a>
            </div>
        </div>

        <div class="clear"></div>
    <?php else: ?>
        <?php $_validateStatus = $_helper->getRussifyStatus($_orderId); ?>

        <?php if($_validateStatus == 'VALID'): ?>
            <div class="f-left validated">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Adress is valid') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
            </div>
        <?php elseif($_validateStatus == 'INVALID'): ?>
            <div class="f-left invalid">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Adress Invalid') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Re-Validate') ?></a>
            </div>
        <?php else:?>
            <div class="f-left not-validated">
                <div class="icon-wrapper">
                    <i class="icon-picture"></i>
                </div>
                <p><?php echo $this->__('Not Validated') ?></p>
            </div>
            <div class="f-right">
                <a class="form-button" href="#" onclick="validate()" ><?php echo $this->__('Validate') ?></a>
            </div>
        <?php endif;?>
    <?php endif; ?>
    <div class="clear"></div>
</div>
